services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    image: backend:pi
    ports:
      - "5000:5000"
    networks:
      - net
  frontend:
    image: frontend:pi
    networks:
      - net
networks:
  net: {}
volumes:
  db-data: {}
