services:
  db:
    env_file:
      - ./.env.prod
  backend:
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5000"]
    env_file:
      - ./.env.prod
  frontend:
    env_file:
      - ./.env.prod
    ports:
      - "80:4000"
