services:
  db:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - net
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: backend/.
    ports:
      - 5000:5000
    networks:
      - net
    environment:
      - FLASK_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres
  frontend:
    build: frontend/.
    ports:
      - 4000:4000
    networks:
      - net
    environment:
      - REACT_APP_BACKEND_ADDRESS=http://0.0.0.0:5000
networks:
  net: {}
volumes:
  db-data: {}
