services:
  db:
    env_file:
      - ./.env.dev
  backend:
    env_file:
      - ./.env.dev
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
  frontend:
    env_file:
      - ./.env.dev
    ports:
      - "4000:4000"
