services:
  db:
    env_file:
      - ./.env.prod
  backend:
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    env_file:
      - ./.env.prod
  frontend:
    env_file:
      - ./.env.prod
    ports:
      - "80:4000"
