"""Add User ID foreign keys

Revision ID: 115b1c79c54e
Revises: c16bb4dcc300
Create Date: 2022-03-11 11:03:13.273134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115b1c79c54e'
down_revision = 'c16bb4dcc300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meetings', 'users', ['user_id'], ['id'])
    op.add_column('notes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    op.add_column('people', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('people', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'people', 'users', ['user_id'], ['id'])
    op.add_column('plans', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'plans', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_column('plans', 'user_id')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.alter_column('people', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('people', 'user_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'user_id')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'user_id')
    # ### end Alembic commands ###
